-- AlterTable
ALTER TABLE `About` ADD COLUMN `facebook` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `instagram` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `telgram` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `twitter` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `whatsapp` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `pdf` VARCHAR(191) NOT NULL DEFAULT '';
