-- AlterTable
ALTER TABLE `About` MODIFY `title` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `desc` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `link` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `headImage` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `myImage` VARCHAR(191) NOT NULL DEFAULT '';
